### ISSUE TITLE
Перенести логику с контроллеров во view.

### ISSUE THREAD

**Issue by ghost** [Yuriu-Zhuravlev/NCTaskManager#10]
В контроллерах реализована логика которая должна быть во вью: вывод в консоль, считывания данных.

**Comment by Yuriu-Zhuravlev** [comment]
Исправлено в коммитах: https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/323debe9f9615cb0fadfa689ad63aaa2b891d95d, https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/5386e7b4ca1e473f7097b5b950b6d2294a6cb1dd
