### ISSUE TITLE
Не информативные сообщения.

### ISSUE THREAD

**Issue by ghost** [Yuriu-Zhuravlev/NCTaskManager#11]
В проекте полно сообщений которые являются неинформативными. 
Например, не понятно что за ошибка и как она произошла.
} catch (IOException e) {
                log.error("Caught exception in EditController ",e);
            }

**Comment by Yuriu-Zhuravlev** [comment]
Исправлено в коммите: https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/654c32c21a62276b9a589926899d862b96d2935b
