### ISSUE TITLE
Нотификации не отображаются при первом запуске программы.

### ISSUE THREAD

**Issue by ghost** [Yuriu-Zhuravlev/NCTaskManager#12]
После первого запуска программы и создания задач не отображаются нотификации. Для воспроизведения удали файл save.dat и запусти приложение.

**Comment by Yuriu-Zhuravlev** [comment]
Исправлено в коммите: https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/68d81d17fe48f66f13beb4e378fc3f03fc26b8a4
