### ISSUE TITLE
Дублирование кода.

### ISSUE THREAD

**Issue by ghost** [Yuriu-Zhuravlev/NCTaskManager#13]
В проекте много кода (в контроллерах), который дублируется. Например, считывания с файла.

**Comment by Yuriu-Zhuravlev** [comment]
Исправлено в коммитах: https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/323debe9f9615cb0fadfa689ad63aaa2b891d95d, https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/5386e7b4ca1e473f7097b5b950b6d2294a6cb1dd, https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/29e75a706fca626be3e8b903ad0c319fdfacea55
