### ISSUE TITLE
Заменить класс ListTypes на enum.

### ISSUE THREAD

**Issue by ghost** [Yuriu-Zhuravlev/NCTaskManager#15]
Нету смысла создавать класс с одним внутренним enum и потом вызывать ListTypes.types.ARRAY
Замени на 
public enum ListTypes {
ARRAY, 
LINKED
}

**Comment by Yuriu-Zhuravlev** [comment]
Исправлено в коммите:
https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/c902ee02222c3da5fa31bf084c30449d9a8a1687
