### ISSUE TITLE
Вынести текстовые константы отдельно.

### ISSUE THREAD

**Issue by ghost** [Yuriu-Zhuravlev/NCTaskManager#9]
В проекте много сообщений, которые дублируются. Вынеси их в отдельный класс, чтобы избежать дублирования.

**Comment by Yuriu-Zhuravlev** [comment]
Исправлено в коммитах: https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/f6e4808f8469f141d612414b87d5b10a9ecb3579, https://github.com/Yuriu-Zhuravlev/NCTaskManager/commit/654c32c21a62276b9a589926899d862b96d2935b
